"""initial schema

Revision ID: 40de73542d9d
Revises: 
Create Date: 2026-08-27 22:01:33.536753
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '40de73542d9d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('encrypted_blob', sa.LargeBinary(), nullable=False),
    sa.Column('expiration_date', sa.String(length=32), nullable=True),
    sa.Column('last_validated_at', sa.String(length=32), nullable=True),
    sa.Column('validation_state', sa.String(length=16), nullable=False),
    sa.Column('last_validation_reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("validation_state IN ('valid','invalid','inconclusive')", name='ck_cookies_validation_state'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cookies_validation_state', 'cookies', ['validation_state'], unique=False)
    op.create_table('daemon_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_running', sa.Boolean(), nullable=False),
    sa.Column('stop_requested', sa.Boolean(), nullable=False),
    sa.Column('daemon_pid', sa.Integer(), nullable=True),
    sa.Column('daemon_started_at', sa.String(length=32), nullable=True),
    sa.Column('last_heartbeat_at', sa.String(length=32), nullable=True),
    sa.Column('db_busy_count_5min', sa.Integer(), nullable=False),
    sa.Column('downloads_paused', sa.Boolean(), nullable=False),
    sa.Column('last_known_good_ytdlp_version', sa.String(length=64), nullable=True),
    sa.Column('last_notified_ytdlp_version', sa.String(length=64), nullable=True),
    sa.Column('last_selfcheck_at', sa.String(length=32), nullable=True),
    sa.Column('last_selfcheck_ok', sa.Boolean(), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_daemon_state_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiktok_video_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiktok_video_id', name='uq_download_archive_video')
    )
    op.create_table('download_pacing_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_allowed_at', sa.String(length=32), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_download_pacing_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitored_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('notify_on_download', sa.Boolean(), nullable=False),
    sa.Column('monitor_after_backfill', sa.Boolean(), nullable=False),
    sa.Column('backfill_status', sa.String(length=16), nullable=False),
    sa.Column('backfill_cursor', sa.String(length=255), nullable=True),
    sa.Column('backfill_total', sa.Integer(), nullable=False),
    sa.Column('backfill_done', sa.Integer(), nullable=False),
    sa.Column('last_check_at', sa.String(length=32), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('total_likes', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('profile_last_refreshed', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("backfill_status IN ('idle','queued','backfilling','paused','completed','failed','cancelled')", name='ck_accounts_backfill_status'),
    sa.CheckConstraint("mode IN ('history', 'monitor')", name='ck_accounts_mode'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_accounts_backfill_status', 'monitored_accounts', ['backfill_status'], unique=False)
    op.create_index('ix_accounts_username', 'monitored_accounts', ['username'], unique=False)
    op.create_table('pending_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiktok_video_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.String(length=8), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('downloaded_at', sa.String(length=32), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_category', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("error_category IN ('definitive','transient','integrity')", name='ck_videos_error_category'),
    sa.CheckConstraint("status IN ('downloaded','failed','cancelled','skipped')", name='ck_videos_status'),
    sa.ForeignKeyConstraint(['account_id'], ['monitored_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiktok_video_id')
    )
    op.create_index('ix_videos_account_downloaded', 'videos', ['account_id', 'downloaded_at'], unique=False)
    op.create_index('ix_videos_tiktok_video_id', 'videos', ['tiktok_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_videos_tiktok_video_id', table_name='videos')
    op.drop_index('ix_videos_account_downloaded', table_name='videos')
    op.drop_table('videos')
    op.drop_table('pending_notifications')
    op.drop_index('ix_accounts_username', table_name='monitored_accounts')
    op.drop_index('ix_accounts_backfill_status', table_name='monitored_accounts')
    op.drop_table('monitored_accounts')
    op.drop_table('download_pacing_state')
    op.drop_table('download_archive')
    op.drop_table('daemon_state')
    op.drop_index('ix_cookies_validation_state', table_name='cookies')
    op.drop_table('cookies')
    # ### end Alembic commands ###
